
DEVICE_ID = "deviceID"
INVALID_DEVICE_ID = "Device ID is invalid"
DEVICE_ID_NOT_REGISTERED = "Device not registered"
UNREGISTERED_ERROR_CODE = 100
ERROR_STATE = 'E'
DEFAULT_DEVICE_MODEL = 'Cutlass'

BACKUPPOWERV = 5 
MAINPOWERV = 8
RSSI = 7
INTERNALTEMPERATUREC = 6
TOW_DETECTION = 2

DEVICE_STATUS_ACTIVE='A'
DEVICE_STATUS_PENDDING='P'
DEVICE_STATUS_ERRORNEOUS='E'

GEOTAB_DELETED_ERROR_CODE = 105